[package]
name = "vrew-auto-editor"
version = "0.2.2"
description = "Vrew project automation desktop app"
authors = ["gabriel.k"]
edition = "2021"

[lib]
name = "vrew_auto_editor_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
